# Generated by Django 5.1.4 on 2024-12-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('goal_type', models.CharField(choices=[('Трата', 'Spending'), ('Пополнение', 'Refill')], default='Трата', max_length=32, verbose_name='Тип операций цели')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Дата начала цели')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания цели')),
                ('value', models.FloatField(verbose_name='Значение цели')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание операции')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('operation_at', models.DateTimeField(default=datetime.datetime(2024, 12, 19, 11, 46, 6, 610338), verbose_name='Дата операции')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
    ]
