# Generated by Django 5.1.4 on 2024-12-19 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_category_alter_operation_operation_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 13, 19, 47, 567523), verbose_name='Дата операции'),
        ),
    ]
