# Generated by Django 5.1.4 on 2024-12-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_operation_operation_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 14, 15, 17, 37645), verbose_name='Дата операции'),
        ),
    ]
